In [12]:
import numpy as np

In [24]:
np.linspace(0,9)

array([0.        , 0.18367347, 0.36734694, 0.55102041, 0.73469388,
       0.91836735, 1.10204082, 1.28571429, 1.46938776, 1.65306122,
       1.83673469, 2.02040816, 2.20408163, 2.3877551 , 2.57142857,
       2.75510204, 2.93877551, 3.12244898, 3.30612245, 3.48979592,
       3.67346939, 3.85714286, 4.04081633, 4.2244898 , 4.40816327,
       4.59183673, 4.7755102 , 4.95918367, 5.14285714, 5.32653061,
       5.51020408, 5.69387755, 5.87755102, 6.06122449, 6.24489796,
       6.42857143, 6.6122449 , 6.79591837, 6.97959184, 7.16326531,
       7.34693878, 7.53061224, 7.71428571, 7.89795918, 8.08163265,
       8.26530612, 8.44897959, 8.63265306, 8.81632653, 9.        ])

In [15]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
2*np.eye(5)

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [18]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [19]:
np.arange(0,12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.arange(2,27).reshape(5,5)

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [21]:
a = np.array([[1,2],[2,3]])
b = np.array([[2,1],[5,4]])

In [22]:
a

array([[1, 2],
       [2, 3]])

In [10]:
b

array([[2, 1],
       [5, 4]])

In [11]:
np.dot(a,b)

array([[12,  9],
       [19, 14]])

In [12]:
a@b

array([[12,  9],
       [19, 14]])

In [13]:
np.multiply(np.dot(a,b),a)

array([[12, 18],
       [38, 42]])

**let us say we have 4 companies with shares 2 millions, 1 million, 800000, 400000. if we purchased 3 shares from the first company, 4 shares from the second, 2 shares from the third, and 6 shares from the last company, so what is the total amount purchased?**

In [40]:
s = np.array([[2000000],[1000000],[800000],[400000]])
p = np.array([[3],[4],[2],[6]])

In [47]:
total = np.dot(s.T,p) #so 4X1 and 1X4 (if we transpose the p then the result will be 4X4)

In [48]:
print("the total is", int(total))

the total is 14000000


In [49]:
x = np.array([[2,1],[3,2]])

In [50]:
x

array([[2, 1],
       [3, 2]])

In [51]:
x_inv = np.linalg.inv(x)

In [52]:
x_inv

array([[ 2., -1.],
       [-3.,  2.]])

In [53]:
from sklearn.datasets import load_digits
x = load_digits().data

In [56]:
x.ndim

2

In [57]:
x.shape

(1797, 64)

In [58]:
x[20].shape

(64,)

In [59]:
x[0][3]

13.0

In [60]:
x[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [61]:
x[9]

array([ 0.,  0., 11., 12.,  0.,  0.,  0.,  0.,  0.,  2., 16., 16., 16.,
       13.,  0.,  0.,  0.,  3., 16., 12., 10., 14.,  0.,  0.,  0.,  1.,
       16.,  1., 12., 15.,  0.,  0.,  0.,  0., 13., 16.,  9., 15.,  2.,
        0.,  0.,  0.,  0.,  3.,  0.,  9., 11.,  0.,  0.,  0.,  0.,  0.,
        9., 15.,  4.,  0.,  0.,  0.,  9., 12., 13.,  3.,  0.,  0.])

In [62]:
x[0] == x[9]

array([ True,  True, False, False, False, False,  True,  True,  True,
       False, False, False, False, False, False,  True,  True,  True,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False,  True,  True,  True, False, False, False, False,  True,
        True])

In [64]:
x[0].max()

15.0

In [66]:
x[0]@x[9] #dot product to find similarity

2807.0

In [ ]:
import sympy as sp # for equations

NameError: name 'np' is not defined