In [1]:
import numpy as np

In [5]:
3*np.eye((3))

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
a = np.array([[3,2],[1,5]])
b = np.array([[2,2],[7,5]])

In [72]:
np.multiply(np.dot(a,b),a)

array([[ 60,  32],
       [ 37, 135]])

In [23]:
P = np.array([[100], [80], [50]])
N = np.array([[3], [4], [5]])

In [28]:
np.dot(P.T, N)

array([[870]])

In [29]:
from sklearn.datasets import load_digits
X=load_digits().data

In [36]:
X@X.T

array([[3070., 1866., 2264., ..., 2812., 3006., 2898.],
       [1866., 4209., 3432., ..., 3906., 3083., 3307.],
       [2264., 3432., 4388., ..., 4005., 3063., 3697.],
       ...,
       [2812., 3906., 4005., ..., 5092., 3729., 4598.],
       [3006., 3083., 3063., ..., 3729., 4316., 3850.],
       [2898., 3307., 3697., ..., 4598., 3850., 4938.]])

In [39]:
a = np.array([[2,0],[0,1]])
np.linalg.inv(a)

array([[0.5, 0. ],
       [0. , 1. ]])

In [7]:
# import numpy as np
# from sklearn.datasets import load_boston
# boston=load_boston()
# X=boston.data
# y=boston.target

In [4]:
# A = X[:,:4], b = y[:4]
# A = A[:, 0,4,5,6]
# Ainv=np.linalg.inv(A), x = np.dot(A, b)

In [6]:
# np.linalg.lstsq(X, y, rcond=None)[0]

In [8]:
a=np.array([[4],[5],[2],[2]])
b=np.array([[4],[0],[2],[0]])
c=np.array([[2],[2],[0],[1]])

In [11]:
temp = a-b
sum_dist = np.dot(temp.T,temp)
np.sqrt(sum_dist)

array([[5.38516481]])

In [12]:
temp = c-b
sum_dist = np.dot(temp.T,temp)
np.sqrt(sum_dist)

array([[3.60555128]])

In [13]:
temp = a-c
sum_dist = np.dot(temp.T,temp)
np.sqrt(sum_dist)

array([[4.24264069]])

In [23]:
a.T@b

array([[20]])

In [21]:
c.T@a

array([[20]])

In [25]:
c.T@b

array([[8]])

In [43]:
import sympy as sp
x,y,k = sp.symbols('x y k')

In [44]:
# f = 1/(1+sp.exp(-x))
# f

In [45]:
f = x**3 - 1
f

x**3 - 1

In [46]:
F_x = sp.diff(f,x)
F_x

3*x**2

In [47]:
f = sp.log(x**2-3*k)
f

log(-3*k + x**2)

In [48]:
fx = sp.diff(f,x)
fx

2*x/(-3*k + x**2)

In [54]:
x,y,a,b = sp.symbols('x y a b')
f = sp.exp(a*x**b)
f

exp(a*x**b)

In [55]:
sp.diff(f,x)

a*b*x**b*exp(a*x**b)/x

In [59]:
f = sp.exp(x**2+2*y**2)
f

exp(x**2 + 2*y**2)

In [60]:
sp.diff(f,x)

2*x*exp(x**2 + 2*y**2)

In [64]:
import sympy

In [65]:
x = sympy.symbols('x')

In [69]:
f=x**3-1
f

x**3 - 1