In [1]:
import numpy as np

In [2]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [3]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [4]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
2*np.eye(5)

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [6]:
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [7]:
np.arange(0,12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
np.arange(2,27).reshape(5,5)

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26]])

In [10]:
 np.arange(27)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [11]:
a = np.array([[1,2],[2,3]])
b = np.array([[2,1],[5,4]])

In [12]:
a

array([[1, 2],
       [2, 3]])

In [13]:
b

array([[2, 1],
       [5, 4]])

In [14]:
a.shape

(2, 2)

In [15]:
np.dot(a,b)

array([[12,  9],
       [19, 14]])

In [16]:
a@b

array([[12,  9],
       [19, 14]])

In [17]:
np.multiply(np.dot(a,b),a)

array([[12, 18],
       [38, 42]])

let us say we have 4 companies with shares 2 millions, 1 million, 800000, 400000. if we purchased 3 shares from the first company, 4 shares from the second, 2 shares from the third, and 6 shares from the last company, so what is the total amount purchased?

In [31]:
S = np.array([200,100,80,40])
P = np.array([3,4,2,6])

In [32]:
S

array([200, 100,  80,  40])

In [33]:
P

array([3, 4, 2, 6])

In [34]:
S.shape

(4,)

In [35]:
P.shape

(4,)

In [36]:
total = np.dot(S.T,P)  #Notice that the first vector is transposed so as we obtain on number as a result

In [37]:
total

1400

In [30]:
print('the total is',float(total))

the total is 1400.0


In [38]:
x = np.array([[2,1],[3,2]])

In [39]:
x

array([[2, 1],
       [3, 2]])

In [40]:
x_inv = np.linalg.inv(x)

In [41]:
x_inv

array([[ 2., -1.],
       [-3.,  2.]])

In [42]:
a = np.dot(x,x_inv)

In [43]:
a

array([[1., 0.],
       [0., 1.]])

In [44]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.array([[1,0,0],[0,1,0],[0,0,1]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
from sklearn.datasets import load_digits
X=load_digits().data


In [47]:
X.ndim  #number of dimensions

2

In [48]:
X.shape

(1797, 64)

In [49]:
X.size

115008

In [50]:
X[20].shape

(64,)

In [51]:
X[0][3]

13.0

In [52]:
X[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [53]:
X[9]

array([ 0.,  0., 11., 12.,  0.,  0.,  0.,  0.,  0.,  2., 16., 16., 16.,
       13.,  0.,  0.,  0.,  3., 16., 12., 10., 14.,  0.,  0.,  0.,  1.,
       16.,  1., 12., 15.,  0.,  0.,  0.,  0., 13., 16.,  9., 15.,  2.,
        0.,  0.,  0.,  0.,  3.,  0.,  9., 11.,  0.,  0.,  0.,  0.,  0.,
        9., 15.,  4.,  0.,  0.,  0.,  9., 12., 13.,  3.,  0.,  0.])

In [54]:
X[0] == X[9]

array([ True,  True, False, False, False, False,  True,  True,  True,
       False, False, False, False, False, False,  True,  True,  True,
       False, False, False, False, False,  True,  True, False, False,
       False, False, False, False,  True,  True, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True,  True, False, False, False, False, False,
       False,  True,  True,  True, False, False, False, False,  True,
        True])

In [55]:
X[0].max()

15.0

In [56]:
X[9].min()

0.0

In [57]:
X[0]@X[9]  #similarity between image 0 and image 9, the first image and the tenth image

2807.0

In [58]:
X[1]@X[9]

2814.0

In [59]:
np.dot(X[0],X[9])

2807.0

In [60]:
matrix = X@X.T  #matrix of similarity

In [61]:
matrix

array([[3070., 1866., 2264., ..., 2812., 3006., 2898.],
       [1866., 4209., 3432., ..., 3906., 3083., 3307.],
       [2264., 3432., 4388., ..., 4005., 3063., 3697.],
       ...,
       [2812., 3906., 4005., ..., 5092., 3729., 4598.],
       [3006., 3083., 3063., ..., 3729., 4316., 3850.],
       [2898., 3307., 3697., ..., 4598., 3850., 4938.]])

In [62]:
matrix.shape

(1797, 1797)

In [63]:
v1 = np.array([2.0, 2.0])
v2 = np.array([3.0, 3.0])
dp = np.dot(v1, v2) #dot product as a test of similarity
print(dp) 

12.0


In [64]:
v1.shape

(2,)

In [65]:
v2.shape

(2,)

In [66]:
v1 = np.array([2.0, 2.0])
v2 = np.array([3.0, -3.0])
dp = np.dot(v1, v2) 
print(dp) #another similarity test example

0.0


In [67]:
from sklearn.datasets import load_boston
boston=load_boston()
X=boston.data
y=boston.target


C:\Users\Mrad\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i

In [68]:
boston.DESCR

".. _boston_dataset:\n\nBoston house prices dataset\n---------------------------\n\n**Data Set Characteristics:**  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000

In [69]:
X.shape

(506, 13)

In [70]:
y.shape

(506,)

In [82]:
np.linalg.lstsq(X,y)[0]  #using least square

C:\Users\Mrad\AppData\Local\Temp\ipykernel_2212\3409810121.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(X,y)[0]  #using least square


array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])

In [20]:
boston.feature_names   #feature or column names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [71]:
A = X[6:10,:]  #choosing rows from 6 to 9, 4 rows
b = y[6:10]   #corresponding output

In [72]:
A

array([[8.8290e-02, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01,
        6.0120e+00, 6.6600e+01, 5.5605e+00, 5.0000e+00, 3.1100e+02,
        1.5200e+01, 3.9560e+02, 1.2430e+01],
       [1.4455e-01, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01,
        6.1720e+00, 9.6100e+01, 5.9505e+00, 5.0000e+00, 3.1100e+02,
        1.5200e+01, 3.9690e+02, 1.9150e+01],
       [2.1124e-01, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01,
        5.6310e+00, 1.0000e+02, 6.0821e+00, 5.0000e+00, 3.1100e+02,
        1.5200e+01, 3.8663e+02, 2.9930e+01],
       [1.7004e-01, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01,
        6.0040e+00, 8.5900e+01, 6.5921e+00, 5.0000e+00, 3.1100e+02,
        1.5200e+01, 3.8671e+02, 1.7100e+01]])

In [74]:
A[3]

array([1.7004e-01, 1.2500e+01, 7.8700e+00, 0.0000e+00, 5.2400e-01,
       6.0040e+00, 8.5900e+01, 6.5921e+00, 5.0000e+00, 3.1100e+02,
       1.5200e+01, 3.8671e+02, 1.7100e+01])

In [75]:
b

array([22.9, 27.1, 16.5, 18.9])

In [76]:
A = A[:4,[0,2,4,6]]  #choosing specified columns or features

In [77]:
A.shape

(4, 4)

In [78]:
Ainv=np.linalg.inv(A)

In [28]:
Ainv

array([[-1.84552940e+00, -2.14878839e+01,  1.22747775e+01,
        -5.42935702e+01],
       [-3.05072309e+15,  1.39893627e+15, -5.18780891e+15,
         6.83959573e+15],
       [ 4.58190663e+16, -2.10107413e+16,  7.79161377e+16,
        -1.02724463e+17],
       [-4.77343590e-02,  7.47333087e-02, -4.84789275e-02,
         2.14799779e-02]])

In [79]:
b.shape

(4,)

In [80]:
Ainv=np.linalg.inv(A)    
x = np.dot(Ainv, b)

In [81]:
x #weight matrix

array([-1.44819893e+03,  1.17191265e+16, -1.76010544e+17,  5.38225121e-01])

In [32]:
xt = x.T

In [33]:
xt.reshape(4,1)

array([[-1.44819893e+03],
       [ 1.17191265e+16],
       [-1.76010544e+17],
       [ 5.38225121e-01]])

In [34]:
A = X[25:29,:]  
b = y[25:29] 

In [35]:
A.shape

(4, 13)

In [36]:
A = A[:4,[0,4,5,6]] 

In [37]:
A.shape

(4, 4)

In [38]:
b.shape

(4,)

In [ ]:
A

In [ ]:
A.shape

In [39]:
Ainv=np.linalg.inv(A)

In [40]:
x = np.dot(Ainv, b)

In [41]:
x

array([ -7.41585725, -20.44226354,   2.56010884,   0.19600015])

In [83]:
a = np.array([[5],[4],[3],[1]])
b = np.array([[2],[0],[3],[0]])
c = np.array([[3],[2],[0],[1]])

In [84]:
dist_a_b  = np.linalg.norm(a-b)   #euclidean distance

In [85]:
dist_a_b

5.0990195135927845

In [86]:
temp = a-b                      #another way to find the euclidean distance
sum_sq = np.dot(temp.T,temp)
print(np.sqrt(sum_sq))

[[5.09901951]]


In [ ]:
np.linalg.norm(temp)

In [ ]:
dist_b_c = np.linalg.norm(b-c)

In [ ]:
dist_b_c

In [ ]:
dist_a_c = np.linalg.norm(a-c)

In [ ]:
dist_a_c

In [87]:
a

array([[5],
       [4],
       [3],
       [1]])

In [88]:
a.shape

(4, 1)

In [89]:
np.linalg.norm(a)

7.14142842854285

In [90]:
np.linalg.norm(b)

3.605551275463989

In [91]:
np.dot(a.T,b)/(np.linalg.norm(a)*np.linalg.norm(b)) #cosine similarity using numpy

array([[0.73789886]])

In [92]:
np.dot(a,b.T)/(np.linalg.norm(a)*np.linalg.norm(b))

array([[0.38836782, 0.        , 0.58255173, 0.        ],
       [0.31069425, 0.        , 0.46604138, 0.        ],
       [0.23302069, 0.        , 0.34953104, 0.        ],
       [0.07767356, 0.        , 0.11651035, 0.        ]])

In [93]:
np.dot(a.T,c)/(np.linalg.norm(a)*np.linalg.norm(c))

array([[0.89817743]])

In [94]:
np.dot(b.T,c)/(np.linalg.norm(b)*np.linalg.norm(c))

array([[0.44474959]])

In [95]:
M = np.array([[1,2],[4,3]])

In [96]:
M

array([[1, 2],
       [4, 3]])

In [97]:
lamda,eigen_v = np.linalg.eig(M)

In [98]:
print('the eigen values are',lamda)

the eigen values are [-1.  5.]


In [99]:
print('the corresponding eigen vectors are',eigen_v)

the corresponding eigen vectors are [[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


In [100]:
M = np.array([[2,3],[3,-6]])

In [101]:
M

array([[ 2,  3],
       [ 3, -6]])

In [102]:
lamda,eigen_v = np.linalg.eig(M)

In [103]:
print('the eigen values are',lamda)

the eigen values are [ 3. -7.]


In [104]:
print('the corresponding eigen vectors are',eigen_v)

the corresponding eigen vectors are [[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]


In [ ]:
np.linalg.eig(M)

In [105]:
import sympy as sp

In [106]:
x,y = sp.symbols('x y')

In [107]:
x

x

In [108]:
f = sp.exp(2*x**2-3*y**2)

In [109]:
f

exp(2*x**2 - 3*y**2)

In [110]:
F_x = sp.diff(f,x)

In [111]:
F_x

4*x*exp(2*x**2 - 3*y**2)

In [112]:
F_y = sp.diff(f,y)

In [113]:
F_y

-6*y*exp(2*x**2 - 3*y**2)

In [114]:
F_xy = sp.diff(f,x,y)

In [115]:
F_xy

-24*x*y*exp(2*x**2 - 3*y**2)

In [116]:
F_yx = sp.diff(f,y,x)

In [117]:
F_yx

-24*x*y*exp(2*x**2 - 3*y**2)

In [118]:
F_xx = sp.diff(f,x,x)

In [119]:
F_xx

4*(4*x**2 + 1)*exp(2*x**2 - 3*y**2)

In [120]:
F_yy = sp.diff(f,y,y)

In [121]:
F_yy

6*(6*y**2 - 1)*exp(2*x**2 - 3*y**2)

In [122]:
x,a,b = sp.symbols('x a b')
f = sp.exp(x**b)
f

exp(x**b)

In [123]:
F_x = sp.diff(f,x)
F_x

b*x**b*exp(x**b)/x

In [125]:
F_x = sp.simplify(sp.diff(f,x))
F_x

b*x**(b - 1)*exp(x**b)

In [126]:
f = sp.exp(3*x**2+2*y**2+1)
f

exp(3*x**2 + 2*y**2 + 1)

In [127]:
F_x = sp.diff(f,x)
F_x

6*x*exp(3*x**2 + 2*y**2 + 1)

In [128]:
F_y = sp.diff(f,y)
F_y

4*y*exp(3*x**2 + 2*y**2 + 1)

In [129]:
F_xx = sp.simplify(sp.diff(f,x,x))
F_xx

(36*x**2 + 6)*exp(3*x**2 + 2*y**2 + 1)

In [130]:
F_yy = sp.simplify(sp.diff(f,y,y))
F_yy

(16*y**2 + 4)*exp(3*x**2 + 2*y**2 + 1)

In [131]:
F_xy = sp.simplify(sp.diff(f,x,y))
F_xy

24*x*y*exp(3*x**2 + 2*y**2 + 1)

In [132]:
F_yx = sp.simplify(sp.diff(f,y,x))
F_yx

24*x*y*exp(3*x**2 + 2*y**2 + 1)

In [133]:
f = sp.exp(x)/(sp.exp(x)+1)
f

exp(x)/(exp(x) + 1)

In [134]:
F_x = sp.diff(f,x)
F_x

exp(x)/(exp(x) + 1) - exp(2*x)/(exp(x) + 1)**2

In [135]:
F_x = sp.simplify(sp.diff(f,x))
F_x

exp(x)/(exp(2*x) + 2*exp(x) + 1)