## Coding Exercise 0101

### 1. NumPy library:

#### 1.1. NumPy basics:

In [2]:
import numpy as np
np.__version__

'1.24.1'

In [3]:
arr1 = np.array([1,3,5,7,9])
arr2 = np.array((1,3,5,7,9))
type(arr1)

numpy.ndarray

In [4]:
arr3 = arr1

In [5]:
id(arr1)

4799577520

In [6]:
id(arr3)

4799577520

In [7]:
arr4 = arr1.copy()

In [8]:
id(arr4)

4411251504

#### 1.2. Creating NumPy arrays:

numpy.arange() function:

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [12]:
arr = np.arange(10) 

In [13]:
len(arr)

10

In [14]:
arr.size 

10

numpy.linspace() function:

In [30]:
np.linspace(1, 10, 5)  # (start, end, number of elements)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [31]:
arr = np.linspace(0, 10, 5, retstep=True) # retstep returns the step size
type(arr)

tuple

In [32]:
arr[0]

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
arr[1]

2.5

numpy.zeros() and numpy.ones() functions:

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.zeros(5, dtype ='int64')

array([0, 0, 0, 0, 0])

In [36]:
np.zeros(5, dtype ='int64').dtype

dtype('int64')

In [38]:
arr = np.ones((2,3), dtype ='int_')

In [39]:
arr

array([[1, 1, 1],
       [1, 1, 1]])

In [40]:
arr.dtype

dtype('int64')

In [41]:
arr.astype('float32')

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

Data type:

In [43]:
arr1 = np.array([111, 2.3,  True, False, False]) 
arr1

array([111. ,   2.3,   1. ,   0. ,   0. ])

In [44]:
arr2 = np.array([111, 2.3, 'python', 'abc']) 
arr2

array(['111', '2.3', 'python', 'abc'], dtype='<U32')

In [45]:
arr3 = np.array([111, True, 'abc']) 
arr3

array(['111', 'True', 'abc'], dtype='<U21')

#### 1.3. Indexing and slicing NumPy arrays:

In [46]:
a = np.array([1, 2, 3, 4, 5])
a[2]

3

In [47]:
a[-1]

5

In [48]:
a[:]

array([1, 2, 3, 4, 5])

In [49]:
a = np.array([[1, 2, 3,], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
a[1]

array([4, 5, 6])

In [51]:
a[-1]

array([7, 8, 9])

In [52]:
a[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
a[2][1]

8

In [54]:
a[2,1]

8

In [55]:
a[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [56]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

Fancy indexing:

In [60]:
arr = np.arange(100)
arrMask = ( (arr % 5) == 0 ) 
arr[arrMask]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [61]:
arrMask = ( ( (arr % 5) == 0 )  & ( arr >0) )
arr[arrMask]

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

#### 1.4. NumPy attributes and reshaping:

In [62]:
a.size

9

In [63]:
a.shape

(3, 3)

In [64]:
a.ndim

2

Change the shape with reshape() method:

In [65]:
a = np.arange(15)
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
# reshape() just produced a 'view'.
# So, there is no permanent change to 'a'.
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [67]:
a = a.reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
a = np.array([2,5,1,3])
a.shape

(4,)

In [69]:
a = a.reshape((2,2))
a

array([[2, 5],
       [1, 3]])

Careful that the reshape() method does not create a new object!

In [75]:
a = np.arange(10)
b = a.reshape(2,5)
a[0] = -999

In [71]:
b

array([[-999,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [78]:
# Make a copy in order to create a new object.
c = a.reshape(2,5).copy()
c[0,0] = 0
a

array([-999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

#### 1.5. Modifying NumPy arrays:

Appending elements, rows and columns to arrays:

In [79]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5, 6])
b

array([1, 2, 3, 4, 5, 6])

In [80]:
a = np.array([[1, 2], [3, 4]])
b = np.append(a, [[9, 9]], axis=0)
b

array([[1, 2],
       [3, 4],
       [9, 9]])

In [82]:
c = np.append(a, [[9], [9]] , axis=1)
c

array([[1, 2, 9],
       [3, 4, 9]])

Deleting array elements, rows and columns:

In [83]:
a = np.array([[1, 2, 3],[4, 5, 6]])
np.delete(a, 0)

array([2, 3, 4, 5, 6])

In [84]:
np.delete(a, (0, 2, 4))

array([2, 4, 6])

In [87]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
np.delete(a, 0, axis = 0)

array([[4, 5, 6]])

In [89]:
np.delete(a, 1, axis = 1)

array([[1, 3],
       [4, 6]])