## Coding Exercise #0102

### 1. NumPy array operations:

#### 1.1. '+' and '*' operators for Python lists:

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]

In [3]:
a + a

[1, 2, 3, 1, 2, 3]

In [4]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
b = np.array([1, 2, 3])

In [6]:
b*3

array([3, 6, 9])

In [7]:
b + b

array([2, 4, 6])

In [8]:
np.repeat(b, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

#### 1.2. '+' and '*' operators for NumPy arrays:

In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [10]:
a+b

array([5, 7, 9])

In [11]:
a-b

array([-3, -3, -3])

In [12]:
a*b

array([ 4, 10, 18])

In [13]:
1.0*a/b

array([0.25, 0.4 , 0.5 ])

#### 1.3. Universal functions:

In [14]:
x = np.array([0, 1, 2, 3, 4, 5])

In [15]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [16]:
np.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,
        54.59815003, 148.4131591 ])

In [17]:
type(np.sqrt)

numpy.ufunc

In [18]:
type(np.exp)

numpy.ufunc

#### 1.4. NumPy functions:

In [32]:
np.random.seed(123) # set seed to get same results
a = np.random.randint(1, 11, size=1000)

In [33]:
a

array([ 3,  3,  7,  2,  4, 10,  7,  2,  1,  2, 10,  1,  1, 10,  4,  5,  1,
        1,  5,  2,  8,  4,  3,  5,  8,  3,  5,  9,  1,  8, 10,  4,  5,  7,
        2,  6,  7,  3,  2,  9,  4,  6,  1,  3,  7,  3,  5,  5,  7,  4,  1,
        7,  5,  8,  7,  8,  2,  6,  8, 10,  3,  5,  9,  2,  3,  2,  2,  4,
        6, 10,  1,  9,  2,  7,  4,  4,  6, 10,  8, 10,  3,  4,  4,  4,  9,
        7, 10,  8,  7,  4, 10,  7,  7,  7,  2,  4,  5,  4,  2,  1,  6,  9,
        7,  9, 10,  2,  1,  4,  2,  4,  5,  8,  7,  2,  5,  4,  4,  8,  7,
        9,  7,  5,  5,  8,  1,  1, 10,  9,  9,  5,  9,  7,  2,  7,  9,  8,
       10,  2,  8,  2,  8, 10,  9,  8,  2,  4,  2,  9,  8,  6,  2,  3,  6,
        3,  3, 10,  4,  3,  7,  8, 10,  2,  4,  9,  4,  8, 10, 10,  4,  4,
        6,  7,  1,  9,  8,  8,  5,  5,  6,  1,  9, 10,  3,  6,  2,  6, 10,
        3,  5,  4,  1,  4,  8,  8,  3,  6,  2,  8,  6, 10,  2,  3,  9,  6,
        1, 10,  4,  4,  4,  2,  8,  7,  4,  2,  8,  3,  7,  6, 10,  9, 10,
        5,  8,  9,  6, 10

In [34]:
np.unique(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
np.median(a) # median (the middle value)

5.0

In [36]:
np.sum(a)

5485

In [37]:
np.round(np.var(a),2)

8.19

In [38]:
np.round(np.mean(a),2)

5.48

In [39]:
np.round(np.std(a),2)

2.86

In [40]:
np.max(a)

10

In [41]:
np.min(a)

1

#### 1.5. Statistical methods of NumPy arrays:

In [43]:
x=np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
x.sum()

55

In [45]:
x.mean()

5.5

In [46]:
x.std()

2.8722813232690143

In [47]:
x.var()

8.25

In [48]:
x.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [49]:
y = np.arange(1,10)
y = y.reshape((3,-1)) # -1 means "whatever is needed" auto find the column but row is 3
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
print(y.mean(axis=0)) # mean of each column

[4. 5. 6.]


In [ ]:
print(y.mean(axis=1)) # mean of each row

In [55]:
z = np.random.randint(10,size=1000)

In [56]:
z.max()

9

In [57]:
z.min()

0

In [58]:
(z > 5).sum()

379

In [59]:
np.unique(z)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
sorted(set(z))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [61]:
a = np.array([2,-3,4,5,7,0,1,-1])

In [62]:
a.argmax() # index of the maximum value

4

In [63]:
a.argmin()

1

In [65]:
b = np.array([2,-1,3,2,-2])

In [66]:
np.where(b == 2) # indices of elements equal to 2

(array([0, 3]),)

In [ ]:
z = np.random.normal(size=1000, loc=10, scale=0.2)
z

In [ ]:
help(np.random.normal)