In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3]) # The array elements are same type
arr_copy = np.copy(arr) # copy the array

In [7]:
set_arr = np.array({1,1,2,3,3,4,4,5,5}) # set (no repeated elements)
set_arr

array({1, 2, 3, 4, 5}, dtype=object)

In [8]:
dict_arr = np.array({'one':1, 'two':2, 'three':3}) # dictionary
dict_arr

array({'one': 1, 'two': 2, 'three': 3}, dtype=object)

In [9]:
np.arange(10) # array of 10 elements
np.arange(1, 10) # array of 9 elements
np.arange(1, 10, 2) # array of 5 elements


array([1, 3, 5, 7, 9])

In [10]:
multi_arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
multi_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.zeros((2,3)) # array of 2 rows and 3 columns


array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
random_arr = np.random.rand(2,3) # array of 2 rows and 3 columns
random_arr
np.mean(random_arr) # mean of the array

0.6601704377211484

In [55]:
a = np.array([[1, 2, 3], [5, 6, 7]])
row = np.append(a, [[1, 2, 3]], axis=0)  # append a row to the array
row
col = np.append(a, [[8],[9]], axis=1) # append a column to the array
col


array([[1, 2, 3, 8],
       [5, 6, 7, 9]])

In [59]:
np.delete(a, 1, axis=0) # delete the second row
np.delete(a, 1, axis=1) # delete the second column

array([[1, 3],
       [5, 7]])

In [78]:
a = np.array([1, 2, 3])
b = np.array([[4, 5, 6],[7,8,9]])
a.shape

(3,)

In [68]:
np.unique(a) # unique elements in the array

array([None], dtype=object)

In [93]:
# a[[0,2]]
# b.shape
b[[0, 0], [1, 0]]
b[b % 2 == 0]  # elements that are even
b[b > 3]  # elements that are greater than 3


array([4, 5, 6, 7, 8, 9])

In [107]:
# slicing
print(a)  # first two elements
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[0, 0:2]  # first two rows and first two columns
a[:, 0:2]  # all the rows and first two columns
a[0,1:]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 3])